[tools]
rust = "1.94.0"
node = "24.14.1"

"npm:@semantic-release/git" = "latest"
"npm:@semantic-release/exec" = "latest"

[tasks."cargo:build"]
run = "cargo build"

[tasks."podman:build"]
run = "podman build -t rustic-prometheus-exporter:local ."

[tasks."docker:build"]
run = "docker build -t rustic-prometheus-exporter:local -f Containerfile ."

[tasks."semantic-release:release"]
run = "npx --yes --package semantic-release@25.0.3 semantic-release"

[tasks."semantic-release:dry-run"]
run = "npx --yes --package semantic-release@25.0.3 semantic-release --dry-run"

[tasks."ci:pull_request"]
depends = ["cargo:build", "docker:build"]

[tasks."ci:release"]
depends = ["semantic-release:release"]
