[tools]
rust = "1.94.0"
node = "24.14.1"
"npm:semantic-release" = "25.0.3"
"npm:@semantic-release/git" = "latest"
minisign = "0.12"

[tasks."cargo:build"]
run = "cargo build"

[tasks."package:archive"]
usage = '''
arg "<target>"
'''
run = """
mkdir -p dist/
cd "./target/${usage_target}/release/"
tar cv "rustic-prometheus-exporter" | gzip -9 > "../../../dist/rust-prometheus-exporter-${usage_target}.tar.gz"
"""
run_windows = """
mkdir dist
cd "target/${env:usage_target}/release/"
7zip a -mx9 "../../../dist/rust-prometheus-exporter-${env:usage_target}.zip" rust-prometheus-exporter.exe
"""

[tasks."package:sign"]
run = """
echo "untrusted comment: minisign encrypted secret key" > ~/rpe-minisign.key
echo "$MINISIGN_SIGNING_KEY" >> ~/rpe-minisign.key
minisign -S -W -s ~/rpe-minisign.key -m dist/*.zip
minisign -S -W -s ~/rpe-minisign.key -m dist/*.tar.gz
rm ~/rpe-minisign.key
"""

[tasks."podman:build"]
run = "podman build -t rustic-prometheus-exporter:local ."

[tasks."docker:build"]
run = "docker build -t rustic-prometheus-exporter:local -f Containerfile ."

[tasks."semantic-release:release"]
run = "npx --yes --package semantic-release@25.0.3 semantic-release"

[tasks."semantic-release:dry-run"]
run = "semantic-release --dry-run"

[tasks."semantic-release:get-next-version"]
run = """
semantic-release --dry-run 2>/dev/null | grep "the next release version is" | sed 's/^.* the next release version is //' > .version
cat .version
"""
