http:
  listen: 0.0.0.0:8080
collector:
  interval: 20s
restic:
  cache_dir: /tmp/rpe-cache
  defaults:
    password: restic
    backend_options:
      rest:
        username: restic
        password: restic
  repositories:
  - name: my-repo
    url: /tmp/my-repo
